#!/usr/bin/env bash
# install HAproxy, configure and starts 'loadbalancer-01' server
apt update
apt-get -y install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get -y install haproxy=2.6.\*
#load balancers configuration
DOMAIN_NAME="osundwa-alx.tech"
INIT_FILE="/etc/default/haproxy"
CONFIG_FILE="/etc/haproxy/haproxy.cfg"
HAPROXY_LB_CONFIG=\
"
defaults
  mode http
  timeout client 10000s
  timeout connect 5000s
  timeout server 10000s

#--$DOMAIN_NAME-params-begin--
backend $DOMAIN_NAME-backend
        balance roundrobin
        server 29642-web-01 3.236.238.180:80 check
        server 29642-web-02 3.236.109.232:80 check
frontend $DOMAIN_NAME-frontend
        bind *:80
        mode http

        default_backend $DOMAIN_NAME-backend
#--$DOMAIN_NAME-params-end--
"

[ -f "$INIT_FILE" ] || touch "$INIT_FILE"
[ -f "$CONFIG_FILE" ] || touch "$CONFIG_FILE"

CONFIG_WORDS=$(grep -Eco "$DOMAIN_NAME-backend" < $CONFIG_FILE)

if [ "$(grep -Eco '^ENABLED=[01]$' < $INIT_FILE)" -gt 0 ]; then
        sed -i 's/^ENABLED=0$/ENABLED=1/' "$INIT_FILE"
else
        echo 'ENABLED=1' >> $INIT_FILE
fi

if [ "$CONFIG_WORDS" -eq 0 ]; then
        echo -e "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
else
        start_tkn="#--$DOMAIN_NAME-params-begin--"
        end_tkn="#--$DOMAIN_NAME-params-end--"
        a=$(grep -onE "$start_tkn" < "$CONFIG_FILE" | cut -d : -f1)
        #echo $a
        b=$(grep -onE "$end_tkn" < "$CONFIG_FILE" | cut -d : -f1)
        #echo $b
        a=$((a - 1))
        b=$((b + 1))
        sed -i "$a,$b"d "$CONFIG_FILE"
        echo -en "$HAPROXY_LB_CONFIG" >> $CONFIG_FILE
fi

if [ "$(pgrep -c haproxy)" -le 0 ]; then
        service haproxy start
else
        service haproxy restart
fi
