#!/bin/bash

# This script takes a list of domains as arguments
# and will setup a single certificate for all of them.

cert_name="generic_cert"
haproxy_cert_dir="/etc/haproxy/ssl"
email="mulamajeff@tuta.io"

domains=""
for domain in "$@"
do
  domains+="-d $domain "
done

certbot certonly --webroot --agree-tos --non-interactive \
--preferred-challenges http \
--http-01-port 54321 --cert-name $cert_name \
--renew-with-new-domains --keep-until-expiring $domains

mkdir -p $haproxy_cert_dir

# Combine the certificate chain and private key and put it
# into the correct HAProxy directory
cd /etc/letsencrypt/live/$cert_name
cat fullchain.pem privkey.pem > "$haproxy_cert_dir/www.osundwa-alx.tech.pem"

echo "Reloading haproxy"
sudo systemctl reload haproxy
